version: '2'
volumes:
    resin-data:
services:
  photo-taker:
    build: ./photo-taker
    volumes:
      - 'resin-data:/data'
    restart: always
    privileged: true
    network_mode: host
    labels:
      io.balena.features.kernel-modules : '1' 
      io.balena.features.supervisor-api: '1'
    cap_add:
      - SYS_RAWIO
    devices:
      - "/dev/mem:/dev/mem"
      - "/dev/gpiomem:/dev/gpiomem"
      - "/dev/i2c-1:/dev/i2c-1"
    ports:
      - "20:20"
      - "21:21"   
  # timelapse-app:
  #   build: ./timelapse-app
  #   volumes:
  #     - 'resin-data:/data'
  #   restart: always
  #   network_mode: host
  #   privileged: true
  #   labels:
  #     io.balena.features.dbus: '1'
  #     io.balena.features.firmware: '1'
  #   ports:
  #     - "80:80"
  wifi-connect:
    build: ./wifi-connect
    restart: always
    network_mode: host
    privileged: true
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.firmware: '1'